config/routes.rb
H4hRestore::Application.routes.draw do
  resources :donors
  resources :donations do
    resources :line_items
  end
  resources :reports

  devise_for :users

  root to: "home#index"
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  paginates_per 10

  attr_accessible :description, :poundage, :donated_on, :donor, :value, :donation_method, :donor_id

  belongs_to :donor
  belongs_to :coordinator, class_name: "Donor"
  has_many :line_items

  validates :poundage, numericality: { greater_than_or_equal_to: 0, message: "must be greater than zero" }
  validates :value, numericality: { greater_than_or_equal_to: 0, message: "must be greater than zero", allow_nil: true }
  validates :donor, presence: true

  def initialize(*args)
    super
    self.donated_on ||= Date.today
  end

  DayResult = Struct.new(:day, :count, :poundage, :value) do
    def attributes
      to_h
    end
  end

  def self.donations_by_day(start_on, end_on)
    between_date = where(:donated_on => start_on.to_date..end_on.to_date)
    between_date.group_by{|d| d.donated_on.strftime("%u")}.sort_by(&:first).map{|key,value| DayResult.new(Date::DAYNAMES[key.to_i], value.count, value.map(&:poundage).sum, value.map(&:value).sum)}
  end

  def self.donations_by_zip(start_on, end_on)
    joins(:donor).select("donors.zipcode as zipcode, count(*) as count, sum(poundage) as poundage, sum(value) as value").where(:donated_on => start_on.to_date..end_on.to_date).group("donors.zipcode").order("zipcode ASC")
  end

  def self.donations_by_top(start_on, end_on, top_type, direct, coordinated)
    #Todo use direct and coordinated params
    top_donors = joins(:donor).select("coalesce(donors.company, donors.name) as name, count(*) as count, sum(poundage) as poundage, sum(value) as value").group("coalesce(donors.company, donors.name)").where(:donated_on => start_on.to_date..end_on.to_date)
    case top_type
      when "Frequency"
        top_donors.order("count desc").limit(100)
      when "Poundage"
        top_donors.order("poundage desc").limit(100)
      when "Value"
        top_donors.order("value desc").limit(100)
      else
        #throw an error
      end    
  end

  PoundageResult = Struct.new(:year, :count, :poundage) do
    def attributes
      to_h
    end
  end
  def self.donations_by_poundage
    #select("strftime('%Y', donated_on) as year, count(*) as count, sum(poundage) as poundage").group("strftime('%Y', donated_on)")
    all.group_by{|d| d.donated_on.strftime("%Y")}.sort_by(&:first).map{|key, value| PoundageResult.new(key, value.count, value.map(&:poundage).sum)}
  end

  def self.units_by_store
   group(:store).sum(:units)
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_filter :authenticate_user!

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donations }
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @donation = Donation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
    @donation = Donation.new
    @donation.donor_id = params[:donor] if params[:donor].present?

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(params[:donation])

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render json: @donation, status: :created, location: @donation }
      else
        format.html { render action: "new" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation, :html => { :class => "form-horizontal"}) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :donor_id %>

  <div class="control-group">
    <label class="control-label">Donor</label>
    <div class="controls">
      <label class="control-label"><%= link_to @donation.donor.name, @donation.donor %></label>
    </div>
  </div>
  <div class="control-group ">
    <%= label_tag :donated_on, "Date", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :donated_on, class: "datepicker" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :poundage, "Est. Weight", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :poundage %>
    </div>
  </div>

  <div class="control-group">
    <%= label_tag :value, "Est. Value", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :value %>
    </div>
  </div>

  <div class="control-group">
    <%= label_tag :coordinator, "Coordinator", :class => 'control-label' %>
    <div class="controls">
      <%= text_field_tag :coordinator, nil, placeholder: "does nothing yet" %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"></label>
    <div class="controls">
      <label class="radio inline">
        <%= f.radio_button 'donation_method', :dropoff %>Drop Off
      </label>
      <label class="radio inline">
       <%= f.radio_button 'donation_method', :pickup %>Pick Up
      </label>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, "Notes", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :rows =>3 %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
    <%= link_to "Cancel", :back, class: "btn" %>
  </div>
<% end %>

app/views/donations/_table.html.erb
<table class="table table-hover table-bordered table-striped restore">
  <tr>
    <th>Date</th>
    <th>Donor</th>
    <th>Coordinator</th>
    <th>Weight</th>
    <th>Value</th>
    <th>Actions</th>
  </tr>

<% donations.each do |donation| %>
  <tr>
    <td><%=donation.donated_on%></td>
    <td>      
      <%= donation.donor.display_name %>
      <%= link_to edit_donor_path(donation.donor) do %>
        <div data-toggle="tooltip" title="view profile" style="float:right" class="h4sprite profile"></div>
      <% end %>
    </td>
    <td><span class="muted">coming soon</span></td>
    <td><%= donation.poundage %></td>
    <td><%= donation.value %></td>
    <td style="width:100px;"><%= link_to edit_donation_path(donation) do %>
            <div data-toggle="tooltip" title="edit" class="h4sprite edit"></div>
        <% end %>
        <%= link_to donation do %>
            <div data-toggle="tooltip" title="print" class="h4sprite printer"></div>
        <% end %>
        <%= link_to donation, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <div data-toggle="tooltip" title="trash" class="h4sprite trash"></div>
        <% end %>
        </td>
    <!--<td><%= link_to 'Show', donation %></td>
    <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
    <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
  </tr>
<% end %>
</table>

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>
<div class="line"></div>

<%= render 'form' %>

<%= form_for [@donation, LineItem.new], html: { class: "form-inline" } do |f| %>
  <%= f.text_field :name, class: "input-xlarge", placeholder: "Item" %>
  <%= f.number_field :quantity, class: "input-small", placeholder: "Quantity" %>
  <%= f.text_field :notes, class: "input-xlarge", placeholder: "Notes" %>
  <%= f.submit "Add Item", class: "btn" %>
<% end %>

<table class="table table-hover table-bordered table-striped restore">
  <tr>
    <th>Item</th>
    <th>Quantity</th>
    <th>Notes</th>
    <th>Actions</th>
  </tr>

  <% @donation.line_items.each do |line_item| %>
    <tr>
      <td><%= line_item.name %></td>
      <td><%= line_item.quantity %></td>
      <td><%= line_item.notes %></td>
      <td style="width:100px;">
        <%= link_to "#" do %>
          <div data-toggle="tooltip" title="edit" class="h4sprite edit"></div>
        <% end %>
        <%= link_to [@donation, line_item], method: :delete, data: { confirm: 'Are you sure?' } do %>
          <div data-toggle="tooltip" title="trash" class="h4sprite trash"></div>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/donations/index.html.erb
<div style="clear:both;"/>
<h1 style="float:left;">Donations</h1>
<div class="pagination-top"><%= paginate @donations %></div>
<div style="clear:both;"/>
<div class="line"></div>

<%= render 'table', donations: @donations %>

<div class="pagination-bottom"><%= paginate @donations %></div>

app/views/donations/new.html.erb
<div class="row">
	<div class="span9"><h1>Donation Detail</h1></div>
	<div class="span3">
		<div class="options">
			<%= link_to @donation, :title => 'Save', :rel => 'tooltip' do %>
				<div class="h4sprite save"></div>
			<% end %>
			<div data-toggle="tooltip" title="print" class="h4sprite printer"></div>
			<div data-toggle="tooltip" title="email" class="h4sprite email"></div>
			<div data-toggle="tooltip" title="trash" class="h4sprite trash"></div>
		</div>
	</div>
</div>
<div class="line"></div>
<%= render 'form' %>
<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Donor:</b>
  <%= link_to @donation.donor.display_name, @donation.donor %>
</p>

<p>
  <b>Poundage:</b>
  <%= @donation.poundage %>
</p>

<p>
  <b>Value:</b>
  <%= @donation.value %>
</p>

<p>
  <b>Method:</b>
  <%= @donation.donation_method %>
</p>

<p>
  <b>Description:</b>
  <%= @donation.description %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation), class: "btn btn-primary" %>
<%= link_to 'Back', donations_path, class: "btn" %>