config/routes.rb
H4hRestore::Application.routes.draw do
  resources :donors
  resources :donations do
    resources :line_items
  end
  resources :reports

  devise_for :users

  root to: "home#index"
end

app/views/layouts/_alerts.html.erb
<% messages.each do |key, message| %>
  <%= content_tag :p, class: "alert alert-#{key}" do %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= message %>
  <% end %>
<% end %>

app/views/layouts/_session.html.erb
<% if user_signed_in? %>
  Signed in as <%= current_user.email %> |
  <%= link_to "Sign out", destroy_user_session_path, data: { method: :delete } %>
<% elsif params[:controller] != 'users' and params[:action] != 'new' %>
  <%= link_to "Sign in " + params[:action], new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>H4hRestore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>



<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">

    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="brand" href="#">Project X</a>

    <div class="nav-collapse">
      <ul class="nav">
        <li class="active"><a href="#">Home</a></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Menu 1
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="nav-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>

      <ul class="nav pull-right">
        <li class="dropdown">
          <a href="properties.php?type=showall" class="dropdown-toggle" data-toggle="dropdown">
            Menu 2
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><a href="propertiesSearch.php">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>

  </div>
</div>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner row">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <div class="offset1 span3 ">
          <a class="brand " href="<%= root_path %>"><%=image_tag("restore_logo.png")%></a>
        </div>
          
          <div class="nav-collapse">   
            <ul class="nav span2 pull-right">
              <li><a data-toggle="tooltip" title="settings" href="#"><div class="h4sprite settings"></div></a></li>
              <li><a data-toggle="tooltip" title="help" href="#"><div class="h4sprite help"></div></a></li>
            </ul>            
            <ul class="nav span6 pull-right">
              <li class="<%= 'active' if params[:controller] == 'donations' %>"><a href="<%=donations_path %>">Donations</a></li>
              <li class="<%= 'active' if params[:controller] == 'donors' %>"><a href="<%=donors_path %>">Donors</a></li>
              <li class="dropdown <%= 'active' if params[:controller] == 'reports' %>">
                  <a data-toggle="dropdown" class="dropdown-toggle">Reports <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                      <% Report.all.each do |report| %>
                        <li><%= link_to( report.name, (report.params ?  edit_report_path(report) : report_path(report))) %></li>
                      <% end %>
                  </ul>
              </li>
              <li class="dropdown <%= 'active' if params[:action] == 'new' %>">
                <a data-toggle="dropdown" class="dropdown-toggle">Create <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Donor", new_donor_path %></li>
                  <li><%= link_to "Donation", new_donation_path%></li>
                </ul>
              </li>           
            </ul>   
          </div><!--/.nav-collapse -->
        </div>
    </div>

    <div class="container">
    <%= render "layouts/alerts", messages: flash %>
      <%= render "layouts/session" %>
      <%= yield %>
    </div> <!-- /container -->
  </body>
</html>